export default {
    USER_AUTH: 'USER_AUTH',
    USER_REG: 'USER_REG',

    CHOOSE_CHAT: 'CHOOSE_CHAT',
    OPEN_CHAT: 'OPEN_CHAT',
    CLOSE_CHAT: 'CLOSE_CHAT',
    ADD_MEMBER: 'ADD_MEMBER',
    NEW_MESSAGE: 'NEW_MESSAGE'
}