export default {
    USER_AUTH: 'USER_AUTH',
    USER_PREFERENCES: 'USER_PREFERENCES',
    ADD_OFFER: 'ADD_OFFER',
    ADD_CHAT: 'ADD_CHAT',
    CLOSE_CHAT: 'CLOSE_CHAT',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL'
}